# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\l1nt3x\PycharmProjects\compilation-of-python-libs-docs\ui\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(481, 760)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        MainWindow.setFont(font)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.libraries_List = QtWidgets.QListWidget(self.centralwidget)
        self.libraries_List.setGeometry(QtCore.QRect(3, 38, 475, 720))
        self.libraries_List.setObjectName("libraries_List")
        self.search_Edit = QtWidgets.QLineEdit(self.centralwidget)
        self.search_Edit.setGeometry(QtCore.QRect(3, 1, 475, 30))
        self.search_Edit.setInputMask("")
        self.search_Edit.setText("")
        self.search_Edit.setObjectName("search_Edit")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CPLD (Main)"))
