# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\l1nt3x\PycharmProjects\compilation-of-python-libs-docs\ui\lib.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.Qt import Qt
from PyQt5.QtCore import QUrl
from PyQt5.QtGui import QDesktopServices
from PyQt5.QtWidgets import QApplication


class plainTextEditWURL(QtWidgets.QPlainTextEdit):

    def mousePressEvent(self, e):
        self.anchor = self.anchorAt(e.pos())
        if self.anchor:
            QApplication.setOverrideCursor(Qt.PointingHandCursor)

    def mouseReleaseEvent(self, e):
        if self.anchor:
            QDesktopServices.openUrl(QUrl(self.anchor))
            QApplication.setOverrideCursor(Qt.ArrowCursor)
            self.anchor = None


class Ui_lib(object):
    def setupUi(self, lib):
        lib.setObjectName("lib")
        lib.resize(760, 470)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(14)
        lib.setFont(font)
        self.listWidget = QtWidgets.QListWidget(lib)
        self.listWidget.setGeometry(QtCore.QRect(3, 3, 541, 61))
        self.listWidget.setObjectName("listWidget")
        self.plainTextEditWURL = QtWidgets.QPlainTextEdit(lib)
        self.plainTextEditWURL.setGeometry(QtCore.QRect(3, 67, 754, 341))
        self.plainTextEditWURL.setObjectName("plainTextEditWURL")
        self.pushButton = QtWidgets.QPushButton(lib)
        self.pushButton.setGeometry(QtCore.QRect(546, 2, 211, 63))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(lib)
        self.pushButton_2.setGeometry(QtCore.QRect(2, 410, 755, 56))
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(lib)
        QtCore.QMetaObject.connectSlotsByName(lib)

    def retranslateUi(self, lib):
        _translate = QtCore.QCoreApplication.translate
        lib.setWindowTitle(_translate("lib", "libName"))
        self.pushButton.setText(_translate("lib", "Save"))
        self.pushButton_2.setText(_translate("lib", "Your templates"))
