# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\l1nt3x\PycharmProjects\compilation-of-python-libs-docs\ui\templates.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_templates(object):
    def setupUi(self, templates):
        templates.setObjectName("templates")
        templates.resize(1200, 720)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(templates.sizePolicy().hasHeightForWidth())
        templates.setSizePolicy(sizePolicy)
        templates.setMinimumSize(QtCore.QSize(1200, 720))
        templates.setMaximumSize(QtCore.QSize(1200, 720))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        templates.setFont(font)
        self.splitter = QtWidgets.QSplitter(templates)
        self.splitter.setGeometry(QtCore.QRect(3, 3, 1194, 714))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.widget = QtWidgets.QWidget(self.splitter)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.listWidget = QtWidgets.QListWidget(self.widget)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout.addWidget(self.listWidget)
        self.widget1 = QtWidgets.QWidget(self.splitter)
        self.widget1.setObjectName("widget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding,
                                           QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton = QtWidgets.QPushButton(self.widget1)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.widget1)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout_2.addWidget(self.plainTextEdit)

        self.retranslateUi(templates)
        QtCore.QMetaObject.connectSlotsByName(templates)

    def retranslateUi(self, templates):
        _translate = QtCore.QCoreApplication.translate
        templates.setWindowTitle(_translate("templates", "Templates"))
        self.pushButton.setText(_translate("templates", "Save"))
